title: "爬墙说"
author: "闲云"
description: "闲聊爬墙以及Nas相关的话题" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "xianyun@paqiang.tk"
#twitter_username: "twitteruser"
github_username: "paqiangtalk"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

## use bluma remote themme
remote_theme: paqiangtalk/bulma-clean-theme
fixed_navbar: top
paginate: 5
paginate_path: "/page:num"


#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
# theme: "minima"

rss: rss

kramdown:
 syntax_highlighter_opts:
   disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
#   - scope:
#       path: ""
#       type: post
#     values:
#       tags: Other
